#服务端设置
server:
  port: 80
  #ip,域名都设置在address
  address: 10.41.2.10
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://10.41.0.14:3306/testzabbix?characterEncoding=utf8&useSSL=false
    username: test
    password: 123456
    #关于数据连接池的配置，不同版本的springboot内置的连接池不一样(可以点击变量看源码，也可以自动提示一个一个找)
    tomcat:
      #在连接归还到连接池时是否测试该连接
      test-on-return: true
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
#HTTP编码设置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true